export const KEY_CODE_ENTER = "Enter"
export const KEY_CODE_ESCAPE = "Escape"
export const KEY_CODE_SPACE = "Space"
export const KEY_CODE_TAB = "Tab"

export const KEY_CODE_D0 = "Digit0"
export const KEY_CODE_D1 = "Digit1"
export const KEY_CODE_D2 = "Digit2"
export const KEY_CODE_D3 = "Digit3"
export const KEY_CODE_D4 = "Digit4"
export const KEY_CODE_D5 = "Digit5"
export const KEY_CODE_D6 = "Digit6"
export const KEY_CODE_D7 = "Digit7"
export const KEY_CODE_D8 = "Digit8"
export const KEY_CODE_D9 = "Digit9"

export const KEY_CODE_A = "KeyA"
export const KEY_CODE_B = "KeyB"
export const KEY_CODE_C = "KeyC"
export const KEY_CODE_D = "KeyD"
export const KEY_CODE_E = "KeyE"
export const KEY_CODE_F = "KeyF"
export const KEY_CODE_G = "KeyG"
export const KEY_CODE_H = "KeyH"
export const KEY_CODE_I = "KeyI"
export const KEY_CODE_J = "KeyJ"
export const KEY_CODE_K = "KeyK"
export const KEY_CODE_L = "KeyL"
export const KEY_CODE_M = "KeyM"
export const KEY_CODE_N = "KeyN"
export const KEY_CODE_O = "KeyO"
export const KEY_CODE_P = "KeyP"
export const KEY_CODE_Q = "KeyQ"
export const KEY_CODE_R = "KeyR"
export const KEY_CODE_S = "KeyS"
export const KEY_CODE_T = "KeyT"
export const KEY_CODE_U = "KeyU"
export const KEY_CODE_V = "KeyV"
export const KEY_CODE_W = "KeyW"
export const KEY_CODE_X = "KeyX"
export const KEY_CODE_Y = "KeyY"
export const KEY_CODE_Z = "KeyZ"

export const KEY_CODE_BACKQUOTE = "Backquote"
export const KEY_CODE_MINUS = "Minus"
export const KEY_CODE_EQUAL = "Equal"

export const KEY_CODE_BRACKET_LEFT = "BracketLeft"
export const KEY_CODE_BRACKET_RIGHT = "BracketRight"
export const KEY_CODE_BACKSLASH = "Backslash"

export const KEY_CODE_SEMICOLON = "Semicolon"
export const KEY_CODE_QUOTE = "Quote"
export const KEY_CODE_COMMA = "Comma"
export const KEY_CODE_PERIOD = "Period"
export const KEY_CODE_SLASH = "Slash"

export const KEY_CODE_ARROW_UP = "ArrowUp"
export const KEY_CODE_ARROW_DOWN = "ArrowDown"
export const KEY_CODE_ARROW_LEFT = "ArrowLeft"
export const KEY_CODE_ARROW_RIGHT = "ArrowRight"
