export const COLOR_DARK = "#555"
export const COLOR_MAIN = "#ddd"
export const COLOR_LIGHT = "#efefef"

export const COLOR_ACCENT = "#039be5"
export const COLOR_BACKGROUND = "#fff"
export const COLOR_CONTRAST = "#fff"
export const COLOR_ERROR = "#d62007"
export const COLOR_SUCCESS = "#22a902"
export const COLOR_TEXT = "#222"
