export const COLOR_DARK = "#555555"
export const COLOR_MAIN = "#dddddd"
export const COLOR_LIGHT = "#efefef"

export const COLOR_ACCENT = "#2196f3"
export const COLOR_BACKGROUND = "#ffffff"
export const COLOR_CONTRAST = "#ffffff"
export const COLOR_ERROR = "#d62007"
export const COLOR_SUCCESS = "#22a902"
export const COLOR_TEXT = "#222222"
