export const COLOR_PRIMARY_DARK = "#555"
export const COLOR_PRIMARY_LIGHT = "#ddd"
export const COLOR_SECONDARY_LIGHT = "#efefef"

export const COLOR_BLACK = "#000"
export const COLOR_BLUE = "#347fc4"
export const COLOR_GREEN = "#2d9e21"
export const COLOR_DARK_GREEN = "#24821a"
export const COLOR_RED = "#ff0033"
export const COLOR_DARK_RED = "#cc0000"
export const COLOR_WHITE = "#fff"
export const COLOR_TRANSPARENT = "transparent"
